### ISSUE TITLE
Intermittent failures to get tabs from chrome

### ISSUE THREAD

**Issue by annagrin** [google/webkit_inspection_protocol.dart#85]
Original issue: https://github.com/flutter/flutter/issues/94886

We see those errors from time to time on our test servers. Looks like sometimes chrome returns html instead of json for the list of tabs - is it possible to catch the error and retry in this case?

```
  [+1744 ms] FormatException: Unexpected character (at character 1)
             <html>
             ^
  
             #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
             #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
             #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
             #3      _parseJson (dart:convert-patch/convert_patch.dart:35:10)
             #4      JsonDecoder.convert (dart:convert/json.dart:612:36)
             #5      JsonCodec.decode (dart:convert/json.dart:216:41)
             #6      jsonDecode (dart:convert/json.dart:155:10)
             #7      ChromeConnection.getTabs (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:44:10)
             <asynchronous suspension>
             #8      ChromeConnection.getTab (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:57:25)
             <asynchronous suspension>
             #9      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:401:9)
             <asynchronous suspension>
             #10     ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:145:17)
             <asynchronous suspension>
             #11     ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
             <asynchronous suspension>
             #12     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
             <asynchronous suspension>
  
  Unable to connect to Chrome debug port: 42255
   FormatException: Unexpected character (at character 1)
  <html>
  ^
  
  
  #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
  #1      ChromiumLauncher._connect (package:flutter_tools/src/web/chrome.dart:406:9)
  <asynchronous suspension>
  #2      ChromiumDevice.startApp (package:flutter_tools/src/web/web_device.dart:145:17)
  <asynchronous suspension>
  #3      ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/isolated/resident_web_runner.dart:307:9)
  <asynchronous suspension>
  #4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:24)
  <asynchronous suspension>
```

**Comment by devoncarew** [comment]
> sometimes chrome returns html instead of json for the list of tabs - is it possible to catch the error and retry in this case?

I think that would be reasonable. The html returned may be some sort of error page? Perhaps there's a race condition w/ chrome's startup.

**Comment by annagrin** [comment]
@devoncarew I suspect you are right about the race condition, hopefully retrying could mitigate the failures and make our tests less flaky.

**Comment by annagrin** [comment]
Also, adding the page to the error message (or at least some part of it) in those situation might help us diagnose the failure.
